### ISSUE TITLE
Provide a way to set the client timeout

### ISSUE THREAD

**Issue by rigolepe** [ITV/scala-pact#53]
The client request timeout is by default at 1 sec and I don't see a way to override this default.

**Comment by davesmith00000** [comment]
Funnily enough, you're the second person to raise this just recently. It's on my radar and @phil-rice has offered to look into it, don't know if he still plans to but if not I'll try and have a look.

There is a question of why this is needed. It sounds reasonable to say "I have services that take varying amounts of time to respond so I may need to manage the timeout" however, Pact tests and verifications are supposed to be run against services in a known state and probably not ones in a live environment. If you're setup is very complicated you could also look at use the provider verification test suites to bypass your slow business logic and only test the API, marshalling, content negotiation and route logic (there's an example in the example projects called provider_test). Just food for thought, I'll still look into it because people are asking.

**Comment by rigolepe** [comment]
Our test setup is fairly simple and it certainly does not run on a live system. However, we have certain calls with a 'sync' option that wait internally on an asynchronous view to update and this can sometimes take more than a second to finish. The async versions of these services are really quick, but our consumer now uses the sync version, so we should really validate their CDC test. A client timeout is a fairly common setting on any http client implementation so it would be great if we could override it :-)

**Comment by davesmith00000** [comment]
Fair enough, I'll see what we can do.

**Comment by davesmith00000** [comment]
Will be in version 2.1.3

**Comment by davesmith00000** [comment]
Hi @rigolepe, can you please verify this works in version 2.1.3?

**Comment by rigolepe** [comment]
I will test this later today.

**Comment by rigolepe** [comment]
OK, it works just fine now. Thanks for the quick release!

**Comment by davesmith00000** [comment]
No worries @rigolepe, as I said a few people were asking and we have @itsDanOades to thank for the fix.

Thanks very much for verifying.
