### ISSUE TITLE
Add support for missing HTTP methods

### ISSUE THREAD

**Issue by k8** [ITV/scala-pact#80]
Support for following HTTP methods is missing: HEAD, CONNECT, PATCH, TRACE. It would be great to have at least support for PATCH as it is quite commonly used in REST APIs.

It looks like changes are needed in following modules:
-scalapact-shared
-scalapact-http4s
-scalapact-scalatest

I could try to create a PR for that. Are there some restrictions that I should be aware of before starting?

**Comment by davesmith00000** [comment]
Hi!

That's a nice isolated change so I'd be very happy for you to have a go at that if you like. Try searching for uses of "Method.OPTIONS" in github for further clues. We added Options later than the others, but it was long ago and the codebase has move around a lot since then...

If you fork the repo and take a branch from either `master` or `v2.2.x`, see how far you get and send in a PR (even incomplete) I'll take a look. I can always help finish it off, and I always test everything to death before a release anyway. Shout if you get stuck.

Fair warning: It can take me a while to review code - I do care I'm just very busy! :-)

Thanks for raising the ticket,

Dave

**Comment by opbokel** [comment]
This pull request should fix it:
https://github.com/ITV/scala-pact/pull/95

I really appreciate if someone can review.

**Comment by opbokel** [comment]
Thanks man!

**Comment by davesmith00000** [comment]
I'm sure you'd rather be hearing that this is about to go out, but just wanted to add that I've back ported this to the 2.2.x version:
https://github.com/ITV/scala-pact/commit/80886dd81a58077f489585d267d7234f659b768d

Will be releasing your fix this week all being well.

**Comment by davesmith00000** [comment]
Fixed for old versions with release `2.2.5`. This is the old slow painful release process. Main branch release should be easier.

**Comment by davesmith00000** [comment]
Released in `2.3.2`, many thanks and apologise for the delay getting it released!
